config/routes.rb
Rails.application.routes.draw do
  get 'jokes/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :recipes
  get '/login' => 'sessions#new'
post '/login' => 'sessions#create'
get '/logout' => 'sessions#destroy'

get '/signup' => 'users#new'
post '/users' => 'users#create'
root "users#new"
get "/auth/:provider/callback" => "sessions#create_from_omniauth"
resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/authentication.rb
class Authentication < ApplicationRecord
  belongs_to :user
  def self.create_with_omniauth(auth_hash)
    self.new(
      provider: auth_hash["provider"],
      uid: auth_hash["uid"],
      token: auth_hash["credentials"]["token"]
    )
  end

  def update_token(auth_hash)
    self.token = auth_hash["credentials"]["token"]
    self.save
  end
end

app/models/joke.rb
class Joke < ApplicationRecord
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :description, presence: true
  mount_uploaders :pictures, RecipePictureUploader

  def self.search(search)
    if search
      where("title ILIKE ?", "%#{search}%")
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password :validations => false
  has_many :authentications, dependent: :destroy
  has_many :recipes, dependent: :destroy
  validates :name, presence: true
  validates :email, presence: true
  validates :password, presence: true
  validates :email, uniqueness: true
  enum access_level: [:user, :admin]

  def self.create_with_auth_and_hash(authentication, auth_hash)
    user = User.create!(name: auth_hash["extra"]["raw_info"]["name"], email: auth_hash["extra"]["raw_info"]["email"], password: SecureRandom.hex(10))
    user.authentications << authentication
    return user
  end

  # grab fb_token to access Facebook for user data
  def fb_token
    x = self.authentications.find_by(provider: 'facebook')
    return x.token unless x.nil?
  end

  def password_optional?
    true
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
    def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
    helper_method :current_user

    def authorize
      redirect_to '/login' unless current_user
    end
end

app/controllers/jokes_controller.rb
class JokesController < ApplicationController
  def index
    @response = HTTParty.get('http://api.icndb.com/jokes/random')
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]

  # GET /recipes
  # GET /recipes.json
  def index
    if params[:search]
      @recipes = Recipe.search(params[:search])
    else
      @recipes = Recipe.all
    end

    respond_to do |format|
      format.js
      format.html
    end
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
    @recipe = Recipe.find(params[:id])
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = current_user.recipes.new(recipe_params)
    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit(:title, :description, :user_id,  {pictures: []})
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to user_path(session[:user_id])
    else
      redirect_to '/login'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/login'
  end

  def create_from_omniauth
     auth_hash = request.env["omniauth.auth"]
     authentication = Authentication.find_by_provider_and_uid(auth_hash["provider"], auth_hash["uid"]) ||  Authentication.create_with_omniauth(auth_hash)

     # if: previously already logged in with OAuth
     if authentication.user
       user = authentication.user
       authentication.update_token(auth_hash)
       @next = recipes_path
       @notice = "Signed in!"
     # else: user logs in with OAuth for the first time
     else

       user = User.create_with_auth_and_hash(authentication, auth_hash)
       # you are expected to have a path that leads to a page for editing user details

       @next = edit_user_path(user.id)
       @notice = "User created. Please confirm or edit details"
     end
     session.clear
     session[:email] = user.email
     session[:name] = user.name
     session[:user_id] = user.id
     signup_url(user)
     redirect_to @next, :notice => @notice
   end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
   @user = User.new
 end

 def create
   @user = User.new(user_params)
   if @user.save
     session[:user_id] = @user.id
     redirect_to user_path(session[:user_id])
   else
     render 'users/new'
   end
 end

 def update
   @user = User.find(current_user.id)
   if @user.update(user_params)
     redirect_to @user, notice: "updated"
   else
     redirect_to @user, notice: "failed"
   end
 end

 def edit
   @user = User.find(params[:id])
 end

 def destroy
  user = User.find(current_user.id)
  user.destroy
  reset_session
  flash[:notice] = "User destroyed."
  redirect_to '/'
 end


 private
   def user_params
     params.require(:user).permit(:name, :email, :password)
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jokes_helper.rb
module JokesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/jokes/index.html.erb
<br>
<h2>Free jokes from this awesome website http://api.icndb.com</h2>
<br>
<p><%= @response.parsed_response["value"]["joke"] %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FreeRecipe</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script type="text/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if current_user %>

      Signed in as <%= current_user.name %> | <%= link_to "Logout", '/logout' %> | <%= link_to "Edit your profile", edit_user_path(current_user.id)%> | <%= link_to "Show Recipe List", recipes_path %> | <%= link_to "free jokes", jokes_index_path %>
      <div>
      <% flash.each do |message_type, message| %>
      <p><%= message %></p>
      <% end %>
    </div>
    <% else %>
      <%= link_to 'Login', '/login' %> | <%= link_to 'Signup', '/signup' %> | <%= link_to "Sign in with Facebook", "/auth/facebook" %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/recipes/_form.html.erb
<%= form_with(model: recipe, local: true) do |f| %>
  <% if recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description, :cols => "50", :rows => "10" %>
  </div>

  <%= f.file_field :pictures, multiple: true %>

  <div class="actions">
    <%= f.submit %>
  </div>


<% end %>

app/views/recipes/_search_results.html.erb
<% if recipes.present? %>
<% recipes.each do |recipe| %>
    <tr>
      <td><%= recipe.title %></td>
      <td><%= recipe.description %></td>

      <% if recipe.pictures? %>
      <td><%= image_tag recipe.pictures.first.thumb %>
        <% else %>
        <td> no picture </td>
        <% end %>
      <td><%= recipe.user.name %></td>
        <td><%= link_to 'Show', recipe %></td>
        <% if current_user.id == recipe.user.id || current_user.admin? == true %>

      <td><%= link_to 'Edit', edit_recipe_path(recipe) %></td>
      <td><%= link_to 'Destroy', recipe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  <% end %>
  <% else %>
  <p> no result found <p>
<% end %>

app/views/recipes/edit.html.erb
<h1>Editing Recipe</h1>

<%= render 'form', recipe: @recipe %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<h1>Recipes</h1>

<%= form_tag recipes_path, :method => 'get', remote: true do %>
  <p>
    <input type="text_field" placeholder="Search For Recipes Title" name="search">
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>


<div>
  <table>
    <thead>
      <tr>
        <th>title</th>
        <th>desciption</th>
        <th>Picture</th>
        <th>Created By</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody id='all_items'>
      <%= render partial: 'search_results', locals: {recipes: @recipes} %>
    </tbody>
  </table>

</div>

<br>

<%= link_to 'New Recipe', new_recipe_path %>

app/views/recipes/index.js.erb
$('#all_items').html("<%=  escape_javascript(render :partial => 'search_results', locals: {recipes: @recipes}) %>")

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= render 'form', recipe: @recipe %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.erb
<table>
  <thead>
    <tr>
      <th>title</th>
      <th>description</th>
      <th>Picture</th>
      <th>Created By</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <td><%= @recipe.title %></td>
        <td><%= @recipe.description %></td>
        <% if @recipe.pictures? %>
        <td>
          <%  @recipe.pictures.each do |x| %>
          <%= image_tag x.normal %>
          <% end %>
          <% else %>
          <td> no picture </td>
          <% end %>
        <td><%= @recipe.user.name %></td>
      </tr>
  </tbody>
</table>

<%= link_to 'Back To Recipe List', recipes_path %>
<% if @recipe.user.id == current_user.id || current_user.admin? == true%>
<%= link_to 'Edit', edit_recipe_path(@recipe) %>
<%= link_to 'Delete', @recipes, method: :delete %>
<% end %>

app/views/users/edit.html.erb
<h1>Edit your profile</h1>


<%= form_for @user do |f| %>

  Name: <%= f.text_field :name %>
  Email: <%= f.text_field :email %>
  Password: <%= f.password_field :password %>
  <%= f.submit "Update Info" %>

<% end %>

<%= link_to "delete", user_path(current_user), method: :delete %>

app/views/users/new.html.erb
<h1>Signup!</h1>

<% @user.errors.full_messages.each do |y| %>
<p><%= y %></p>
<% end %>

<%= form_for @user do |f| %>
<div class="field">
  <%= f.label :name %>
  <%= f.text_field :name %>
</div>

<div class="filed">
  <%= f.label :email %>
  <%= f.text_field :email %>
</div>

<div class="filed">
  <%= f.label :password %>
  <%= f.password_field :password %>
</div>

  <%= f.submit "Submit" %>
<% end %>

app/views/users/show.html.erb
<p> hi, <%= current_user.email %> </p>